In [2]:
import pandas as pd
import numpy as np
from pathlib import Path

In [3]:
dfolder = Path('./datasets')
train_data = 'train.csv'
df_train = pd.read_csv(dfolder/train_data)
df_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [5]:
df_train.nunique()

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

In [6]:
df_train['Cabin'].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64',

In [7]:
df1 = df_train.copy()
df1['Cabin'].fillna('XXXXX', inplace=True)

In [8]:
df1.Cabin.unique()

array(['XXXXX', 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C

In [9]:
df1['Cabin1'] = df1['Cabin'].str[0]
df1.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare  Cabin Embarked Cabin1  
0      0         A/5 21171   7.2500  XXXXX        S      X  
1      0          PC 17599  71.2833    C85        C      C  
2      0  STON/O2. 3101282   7.9250  XXXXX        S      X  
3      0            113803  53.1000   C123        S      C  
4      0            373450   8.0500  XXXXX        S      X

## Chi2 test - Cabin

In [10]:
ctable = pd.crosstab(df1['Cabin1'], df1['Survived'], margins=True)
print(ctable)

Survived    0    1  All
Cabin1                 
A           8    7   15
B          12   35   47
C          24   35   59
D           8   25   33
E           8   24   32
F           5    8   13
G           2    2    4
T           1    0    1
X         481  206  687
All       549  342  891


In [11]:
from scipy.stats import chi2_contingency

In [12]:
def chi2_test(contingency_table):
    # Perform the chi-square test
    chi2, p, dof, expected = chi2_contingency(ctable)

    # Print the test results
    print(f'Chi-squared value: {chi2}')
    print(f'p-value: {p}')
    print(f'Degrees of freedom: {dof}')
    print('Expected frequencies:')
    print(expected)

In [13]:
chi2_test(ctable)

Chi-squared value: 99.16416061888009
p-value: 3.1504485017675686e-13
Degrees of freedom: 18
Expected frequencies:
[[9.24242424e+00 5.75757576e+00 1.50000000e+01]
 [2.89595960e+01 1.80404040e+01 4.70000000e+01]
 [3.63535354e+01 2.26464646e+01 5.90000000e+01]
 [2.03333333e+01 1.26666667e+01 3.30000000e+01]
 [1.97171717e+01 1.22828283e+01 3.20000000e+01]
 [8.01010101e+00 4.98989899e+00 1.30000000e+01]
 [2.46464646e+00 1.53535354e+00 4.00000000e+00]
 [6.16161616e-01 3.83838384e-01 1.00000000e+00]
 [4.23303030e+02 2.63696970e+02 6.87000000e+02]
 [5.49000000e+02 3.42000000e+02 8.91000000e+02]]


### Conclusion

p-value <0.0000 signifies high correlation with Survival. 

In [14]:
ctable1 = pd.crosstab(df1['Cabin'], df1['Survived'], margins=True)

In [15]:
chi2_test(ctable1)

Chi-squared value: 99.16416061888009
p-value: 3.1504485017675686e-13
Degrees of freedom: 18
Expected frequencies:
[[9.24242424e+00 5.75757576e+00 1.50000000e+01]
 [2.89595960e+01 1.80404040e+01 4.70000000e+01]
 [3.63535354e+01 2.26464646e+01 5.90000000e+01]
 [2.03333333e+01 1.26666667e+01 3.30000000e+01]
 [1.97171717e+01 1.22828283e+01 3.20000000e+01]
 [8.01010101e+00 4.98989899e+00 1.30000000e+01]
 [2.46464646e+00 1.53535354e+00 4.00000000e+00]
 [6.16161616e-01 3.83838384e-01 1.00000000e+00]
 [4.23303030e+02 2.63696970e+02 6.87000000e+02]
 [5.49000000e+02 3.42000000e+02 8.91000000e+02]]


## Chi2 Test - Sex

In [16]:
ctable2 = pd.crosstab(df1['Survived'], df1['Sex'], margins=True)
print(ctable2)

Sex       female  male  All
Survived                   
0             81   468  549
1            233   109  342
All          314   577  891


In [17]:
chi2_test(ctable2)

Chi-squared value: 99.16416061888009
p-value: 3.1504485017675686e-13
Degrees of freedom: 18
Expected frequencies:
[[9.24242424e+00 5.75757576e+00 1.50000000e+01]
 [2.89595960e+01 1.80404040e+01 4.70000000e+01]
 [3.63535354e+01 2.26464646e+01 5.90000000e+01]
 [2.03333333e+01 1.26666667e+01 3.30000000e+01]
 [1.97171717e+01 1.22828283e+01 3.20000000e+01]
 [8.01010101e+00 4.98989899e+00 1.30000000e+01]
 [2.46464646e+00 1.53535354e+00 4.00000000e+00]
 [6.16161616e-01 3.83838384e-01 1.00000000e+00]
 [4.23303030e+02 2.63696970e+02 6.87000000e+02]
 [5.49000000e+02 3.42000000e+02 8.91000000e+02]]


### Conclusion
p-value of <0.0000 signifies that Sex is highly correlated to survival. 

In [18]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    object 
 11  Embarked     889 non-null    object 
 12  Cabin1       891 non-null    object 
dtypes: float64(2), int64(5), object(6)
memory usage: 90.6+ KB


In [19]:
df1.Pclass.unique()
df1.Pclass.value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [20]:
corr1 = df1[['Survived', 'Pclass']].corr()
print(corr1)

          Survived    Pclass
Survived  1.000000 -0.338481
Pclass   -0.338481  1.000000


### Conclusion

There is a weak correlation between Pclass and Survived when treated as numerical. 

In [21]:
ctable3 = pd.crosstab(df1['Survived'], df1['Pclass'], margins=True)
print(ctable3)

Pclass      1    2    3  All
Survived                    
0          80   97  372  549
1         136   87  119  342
All       216  184  491  891


In [22]:
chi2_test(ctable3)

Chi-squared value: 99.16416061888009
p-value: 3.1504485017675686e-13
Degrees of freedom: 18
Expected frequencies:
[[9.24242424e+00 5.75757576e+00 1.50000000e+01]
 [2.89595960e+01 1.80404040e+01 4.70000000e+01]
 [3.63535354e+01 2.26464646e+01 5.90000000e+01]
 [2.03333333e+01 1.26666667e+01 3.30000000e+01]
 [1.97171717e+01 1.22828283e+01 3.20000000e+01]
 [8.01010101e+00 4.98989899e+00 1.30000000e+01]
 [2.46464646e+00 1.53535354e+00 4.00000000e+00]
 [6.16161616e-01 3.83838384e-01 1.00000000e+00]
 [4.23303030e+02 2.63696970e+02 6.87000000e+02]
 [5.49000000e+02 3.42000000e+02 8.91000000e+02]]


### Conclusion

p-value <0.0000 suggests Pclass is highly correlated as a category

In [23]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    object 
 11  Embarked     889 non-null    object 
 12  Cabin1       891 non-null    object 
dtypes: float64(2), int64(5), object(6)
memory usage: 90.6+ KB


In [24]:
corr = df1[['Survived', 'Age']].corr()
print(corr)

          Survived       Age
Survived  1.000000 -0.077221
Age      -0.077221  1.000000


In [25]:
df1['Age'].unique()
df1.Age.describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [26]:
df1['Age'] = df1['Age'].fillna(df1['Age'].median())
df1.Age.describe()

count    891.000000
mean      29.361582
std       13.019697
min        0.420000
25%       22.000000
50%       28.000000
75%       35.000000
max       80.000000
Name: Age, dtype: float64

In [27]:
corr = df1[['Survived', 'Age']].corr()
print(corr)

          Survived      Age
Survived   1.00000 -0.06491
Age       -0.06491  1.00000


In [28]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    object 
 11  Embarked     889 non-null    object 
 12  Cabin1       891 non-null    object 
dtypes: float64(2), int64(5), object(6)
memory usage: 90.6+ KB


### Conclussion 

There does not appear to be a strong correlation with Age and Survival even after converting NaNs to median. 

### Test

features = ['Pclass', 'Sex', 'Age', 'Cabin']
y = ['Survived']

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score


In [30]:
def rf_class(X_list, y, **kwargs):
    # Set default kwargs
    defaults = {
        'test_size': 0.2, 
        'random_state': 42, 
        'n_estimators': 100
    }
    # Update defaults
    defaults.update(kwargs)

    X_train, X_test, y_train, y_test = train_test_split(X_list, y, test_size = defaults['test_size'], random_state = defaults['random_state'])

    model = RandomForestClassifier(n_estimators=defaults['n_estimators'], random_state=defaults['random_state'])

    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)
    print(accuracy)
    

In [31]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    object 
 11  Embarked     889 non-null    object 
 12  Cabin1       891 non-null    object 
dtypes: float64(2), int64(5), object(6)
memory usage: 90.6+ KB


In [32]:
data = df1[['Survived', 'Pclass', 'Sex', 'Age', 'Cabin1']]
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       891 non-null    float64
 4   Cabin1    891 non-null    object 
dtypes: float64(1), int64(2), object(2)
memory usage: 34.9+ KB


In [33]:
from sklearn.preprocessing import OneHotEncoder

In [34]:
# Initialize encoder 
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

# Fit and transform categorical features
encoded_features = encoder.fit_transform(data[['Sex', 'Cabin1']])

# Convert the encoded features to a DF w appropriate column names
encoded_df = pd.DataFrame(encoded_features, columns=encoder.get_feature_names_out(['Sex', 'Cabin1']))

# Combine the one-hot encoded features w original dataframe
result_df = pd.concat([data, encoded_df], axis=1)

# Drop original categorial columns (optional)
result_df = result_df.drop(columns=['Sex', 'Cabin1'])

# Print resulting dataframe
print(result_df)

     Survived  Pclass   Age  Sex_female  Sex_male  Cabin1_A  Cabin1_B  \
0           0       3  22.0         0.0       1.0       0.0       0.0   
1           1       1  38.0         1.0       0.0       0.0       0.0   
2           1       3  26.0         1.0       0.0       0.0       0.0   
3           1       1  35.0         1.0       0.0       0.0       0.0   
4           0       3  35.0         0.0       1.0       0.0       0.0   
..        ...     ...   ...         ...       ...       ...       ...   
886         0       2  27.0         0.0       1.0       0.0       0.0   
887         1       1  19.0         1.0       0.0       0.0       1.0   
888         0       3  28.0         1.0       0.0       0.0       0.0   
889         1       1  26.0         0.0       1.0       0.0       0.0   
890         0       3  32.0         0.0       1.0       0.0       0.0   

     Cabin1_C  Cabin1_D  Cabin1_E  Cabin1_F  Cabin1_G  Cabin1_T  Cabin1_X  
0         0.0       0.0       0.0       0.0    

In [35]:
features = ['Pclass', 'Sex', 'Age', 'Cabin1']
X = result_df.iloc[:, 1:]
y = result_df['Survived']
print(X)

     Pclass   Age  Sex_female  Sex_male  Cabin1_A  Cabin1_B  Cabin1_C  \
0         3  22.0         0.0       1.0       0.0       0.0       0.0   
1         1  38.0         1.0       0.0       0.0       0.0       1.0   
2         3  26.0         1.0       0.0       0.0       0.0       0.0   
3         1  35.0         1.0       0.0       0.0       0.0       1.0   
4         3  35.0         0.0       1.0       0.0       0.0       0.0   
..      ...   ...         ...       ...       ...       ...       ...   
886       2  27.0         0.0       1.0       0.0       0.0       0.0   
887       1  19.0         1.0       0.0       0.0       1.0       0.0   
888       3  28.0         1.0       0.0       0.0       0.0       0.0   
889       1  26.0         0.0       1.0       0.0       0.0       1.0   
890       3  32.0         0.0       1.0       0.0       0.0       0.0   

     Cabin1_D  Cabin1_E  Cabin1_F  Cabin1_G  Cabin1_T  Cabin1_X  
0         0.0       0.0       0.0       0.0       0.0    

In [36]:
rf_class(X, y, test_size=0.5, random_state=100)

0.7959641255605381


In [38]:
result_df.columns

Index(['Survived', 'Pclass', 'Age', 'Sex_female', 'Sex_male', 'Cabin1_A',
       'Cabin1_B', 'Cabin1_C', 'Cabin1_D', 'Cabin1_E', 'Cabin1_F', 'Cabin1_G',
       'Cabin1_T', 'Cabin1_X'],
      dtype='object')

### Conclusion

Using RandomForestClassifier and OneHotEncode columns: Cabin1 and Sex, the accuracy has improved to 0.80. 

In [39]:
result_df1 = result_df.drop(columns=['Sex_female', 'Cabin1_X'])

In [40]:
result_df1.columns

Index(['Survived', 'Pclass', 'Age', 'Sex_male', 'Cabin1_A', 'Cabin1_B',
       'Cabin1_C', 'Cabin1_D', 'Cabin1_E', 'Cabin1_F', 'Cabin1_G', 'Cabin1_T'],
      dtype='object')

In [41]:
X1= result_df1.iloc[:, 1:]
y1 = result_df1['Survived']


In [42]:
rf_class(X1, y1, test_size=0.5, random_state=100)

0.7959641255605381


In [52]:
rf_class(X1, y1, test_size=0.35, random_state=100)

0.8076923076923077


In [59]:
rf_class(X1, y1, test_size=0.20, random_state=100)

0.8156424581005587


In [55]:
rf_class(X1, y1, test_size=0.5, random_state=42)

0.7959641255605381


In [58]:
rf_class(X1, y1, test_size=0.10, random_state=42)

0.7666666666666667
